name: ScrollPad
options:
  bundleIdPrefix: com.scrollpad
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual
    PRODUCT_NAME: ScrollPad

targets:
  ScrollPad:
    type: application
    platform: macOS
    sources:
      - path: ScrollPad/Sources
        type: group
      - path: ScrollPad/Resources
        type: group
    settings:
      base:
        INFOPLIST_FILE: ScrollPad/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.scrollpad.app
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: ScrollPad/Resources/ScrollPad.entitlements
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
    entitlements:
      path: ScrollPad/Resources/ScrollPad.entitlements
